loosk like variable set in while loop are ignore , may be due to IFS

diff --git a/jenkins-backup b/jenkins-backup
--- a/jenkins-backup
+++ b/jenkins-backup
@@ -175,17 +175,19 @@ grep -v '\.xml$' files.conf | while IFS= read -r file; do
   ${script_dir}/jenkins-encrypt.py -P $LOCALCLI_KEY "${file}"
 done
 
-rm -f files.conf
-XFILES="false"
+rm -f files.conf jenkins-backup-invalid-files.txt
 grep -Ri 'token\|pass\|secret' --exclude-dir=.git --include='*.xml' --include='contents' $GIT_DIR | grep ': *<' | grep -v ': *<[^>]*> *$' | while IFS= read -r data ; do
   f=$(echo $data | sed 's|:.*||')
   d=$(echo $data | sed 's|.*:||')
   [ $(echo $d | grep -f ${script_dir}/etc/pass_keys.txt | wc -l) -gt 0 ] && continue
-  if [ "$XFILES" = "false" ] ; then echo "ERROR: Found files with secrets/token/password in them" ; fi
-  echo $data
-  XFILES="true"
+  echo "$data" >> jenkins-backup-invalid-files.txt
 done
-if [ "$XFILES" = "false" ] ; then exit 1 ;fi
+if [ -f jenkins-backup-invalid-files.txt ] ; then
+  echo "ERROR: Found files with secrets/token/password in them"
+  cat jenkins-backup-invalid-files.txt
+  rm -f jenkins-backup-invalid-files.txt
+  exit 1
+fi
 
 if $PUSH_CHG ; then
   git add . || true
