use jenkins prefix from JENKINS_HOME/jenkins_prefix

diff --git a/jenkins-backup b/jenkins-backup
--- a/jenkins-backup
+++ b/jenkins-backup
@@ -4,11 +4,17 @@ PUSH_CHG=$2
 JENKINS_HOME=/var/lib/jenkins
 script_dir=$(dirname $0)
 LOCALCLI_KEY=${JENKINS_HOME}/.ssh/id_dsa
-branch=$(java -jar ${JENKINS_HOME}/jenkins-cli.jar -i $LOCALCLI_KEY -s http://localhost:8080/jenkins version | cut -d. -f1,2 | sed 's|.$||;s|\.$|\.0|')
-GIT_BRANCH=jenkins${branch}
-GIT_DIR=${JENKINS_HOME}/gitlab/cmsjenkins-${branch}
+jenkins_prefix=$(cat ${JENKINS_HOME}/jenkins_prefix)
+if [ "${jenkins_prefix}" = "" ] ; then
+  echo "ERROR: Empty ${JENKINS_HOME}/jenkins_prefix. Please populate it with jenkins prefix e.g. jenkins and then run"
+  exit 1
+fi
+branch=$(java -jar ${JENKINS_HOME}/jenkins-cli.jar -i $LOCALCLI_KEY -s http://localhost:8080/${jenkins_prefix} version | cut -d. -f1,2 | sed 's|.$||;s|\.$|\.0|')
+GIT_BRANCH=${jenkins_prefix}${branch}
+GIT_DIR=${JENKINS_HOME}/gitlab/cmsjenkins-${GIT_BRANCH}
 
 if [ ! -d $GIT_DIR ] ; then
+  mkdir -p ${JENKINS_HOME}/gitlab
   git clone https://:@gitlab.cern.ch:8443/cms-sw/cmsjenkins.git $GIT_DIR
 fi
 cd $GIT_DIR
@@ -55,7 +61,7 @@ for s in ${JENKINS_SECRETS_FILES} ; do
   openssl enc -e -a -base64 -aes-256-cbc -salt -in $key -out ${ekey} -pass file:$LOCALCLI_KEY
 done
 
-java -jar  $JENKINS_HOME/jenkins-cli.jar -i $LOCALCLI_KEY -s http://localhost:8080/jenkins -remoting groovy $script_dir/get_plugins.groovy | grep -v 'scriptler' | sort > $GIT_DIR/pluginslist
+java -jar  $JENKINS_HOME/jenkins-cli.jar -i $LOCALCLI_KEY -s http://localhost:8080/${jenkins_prefix} -remoting groovy $script_dir/get_plugins.groovy | grep -v 'scriptler' | sort > $GIT_DIR/pluginslist
 
 if [ $(grep ':' $GIT_DIR/pluginslist | wc -l) -eq 0 ] ; then
   echo "ERROR: unable to get plugins"
diff --git a/jenkins-restore b/jenkins-restore
--- a/jenkins-restore
+++ b/jenkins-restore
@@ -2,15 +2,24 @@
 JENKINS_HOME=$1
 REPO=$2
 script_dir=$(dirname $0)
-branch=$(java -jar ${JENKINS_HOME}/jenkins-cli.jar -s http://localhost:8080/jenkins version | cut -d. -f1,2 | sed 's|.$||;s|\.$|\.0|')
+jenkins_prefix=$(cat ${JENKINS_HOME}/jenkins_prefix)
+if [ "${jenkins_prefix}" = "" ] ; then
+  echo "ERROR: Empty ${JENKINS_HOME}/jenkins_prefix. Please populate it with jenkins prefix e.g. jenkins and then run"
+  exit 1
+fi
+branch=$(java -jar ${JENKINS_HOME}/jenkins-cli.jar -s http://localhost:8080/${jenkins_prefix} version | cut -d. -f1,2 | sed 's|.$||;s|\.$|\.0|')
 if [ "X$branch" = "X" ] ; then 
   echo "Error: Unable to find jenkins version"
   exit 1
 fi
-GIT_BRANCH=jenkins${branch}
-GIT_DIR=${JENKINS_HOME}/plugin-ref/cmsjenkins-${branch}
+GIT_BRANCH=${jenkins_prefix}${branch}
+GIT_DIR=${JENKINS_HOME}/plugin-ref/cmsjenkins-${GIT_BRANCH}
 if [ ! -d $GIT_DIR ] ; then
-  git clone --depth 1 -b $GIT_BRANCH $REPO $GIT_DIR
+  git clone --depth 1 -b $REPO $GIT_DIR
+  pushd $GIT_DIR
+    if [ $(git branch -a | grep "remotes/origin/${GIT_BRANCH}$" | wc -l) = 0 ] ; then GIT_BRANCH=jenkins${branch} ; fi
+    git checkout $GIT_BRANCH
+  popd
 fi
 
 find $GIT_DIR -name '*.xml' -type f | xargs grep ' plugin=' | sed 's|.* plugin="||;s|@.*||' | grep -v '^pipeline-' > $GIT_DIR/plugin.used
