allow to pass backup repo

diff --git a/jenkins-backup b/jenkins-backup
--- a/jenkins-backup
+++ b/jenkins-backup
@@ -2,13 +2,18 @@
 FORCE_ENC=$1
 PUSH_CHG=$2
 FORCE_PUSH=$3
+BACK_REPO=$4
+if [ "X$BACK_REPO" = "X" ] ; then BACK_REPO=https://:@gitlab.cern.ch:8443/cms-sw/cmsjenkins.git ; fi
 JENKINS_HOME=/var/lib/jenkins
 script_dir=$(dirname $0)
 LOCALCLI_KEY=${JENKINS_HOME}/.ssh/id_dsa
-jenkins_prefix=$(cat ${JENKINS_HOME}/jenkins_prefix)
-if [ "${jenkins_prefix}" = "" ] ; then
-  echo "ERROR: Empty ${JENKINS_HOME}/jenkins_prefix. Please populate it with jenkins prefix e.g. jenkins and then run"
-  exit 1
+jenkins_prefix="jenkins"
+if [ -e ${JENKINS_HOME}/jenkins_prefix ] ; then
+  jenkins_prefix=$(cat ${JENKINS_HOME}/jenkins_prefix)
+  if [ "${jenkins_prefix}" = "" ] ; then
+    echo "ERROR: Empty ${JENKINS_HOME}/jenkins_prefix. Please populate it with jenkins prefix e.g. jenkins and then run"
+    exit 1
+  fi
 fi
 branch=$(java -jar ${JENKINS_HOME}/jenkins-cli.jar -i $LOCALCLI_KEY -s http://localhost:8080/${jenkins_prefix} version | cut -d. -f1,2 | sed 's|.$||;s|\.$|\.0|')
 GIT_BRANCH=${jenkins_prefix}${branch}
@@ -16,7 +21,7 @@ GIT_DIR=${JENKINS_HOME}/jenkins-backup/${GIT_BRANCH}
 
 if [ ! -d $GIT_DIR ] ; then
   mkdir -p ${JENKINS_HOME}/jenkins-backup
-  git clone https://:@gitlab.cern.ch:8443/cms-sw/cmsjenkins.git $GIT_DIR
+  git clone $BACK_REPO $GIT_DIR
 fi
 cd $GIT_DIR
 if [ $(git branch -a | grep remotes/origin/${GIT_BRANCH} | wc -l) -gt 0 ] ; then
